# Site settings
title: nagyova.net
email: laser@nagyova.net
#description: "Even if you're not doing anything wrong, you are being watched and recorded. 'Edward Snowden'"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nagyova.net" # the base hostname & protocol for your site
#github_username:  mygithub
facebook_username:  nxedit

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate

paginate: 9
paginate_path: "/page:num/"

timezone: Europe/Bratislava
